### PR TITLE
GEODE-7716: Use gradlew that does not require a checked in jar

### PR DESCRIPTION
**Pull request by upthewaterspout**
When publishing a source distribution, we should not include any jars in the
distribution. For other geode projects, we use this gradlew
which downloads the gradle-wrapper.jar file was well.

I took this gradlew script from geode-examples.

### CODE REVIEW

**Comment by onichols-pivotal** [comment]
Looks good.  By the way we still have `gradlew.bat` on Geode which is set up the old way (expects `gradle\wrapper\gradle-wrapper.jar` to be checked in).  I think probably we should try to find a more modern `gradlew.bat` for both Geode and here...?  Or consider deleting the broken one from Geode?

**Comment by onichols-pivotal** [comment]
I would also suggest bumping `gradle/wrapper/gradle-wrapper.properties` from 5.0 to 5.4 to match `geode` and `geode-examples`

**Comment by rhoughton-pivot** [comment]
Do you want to do this to geode itself as well?

**Comment by onichols-pivotal** [comment]
Deleting the gradle wrapper jar still breaks `gradlew.bat` ...

**Comment by upthewaterspout** [comment]
@rhoughton-pivot - geode already using this same wrapper, just the geode-benchmarks project was inconsistent.

@onichols-pivotal - I deleted gradlew.bat - that is also consistent with what we did with geode-examples.

**Comment by onichols-pivotal** [comment]
last I checked, geode is *not* already using the same wrapper as geode-examples.

I personally am fine with deleting gradlew.bat...I would hope windows developers are at least using  cygwin...but that seems worthy of a dev list discussion before just dropping it

**Comment by upthewaterspout** [comment]
@onichols-pivotal - Oh yeah, you're right. The geode repo does some more complicated gradle magic. It has the the normal gradlew checked in at the root, but then when it creates the source distribution it replaces it with geode-assembly/src/src/dist/gradlew. I think for these auxiliary projects we decided that was overkill, which is why geode-examples and now geode-benchmarks just use that same geode-assembly/src/src/dist/gradlew at the root in git.

**Pull request merged**
