### PR TITLE
GEODE-9788 pubsub benchmark

### PR DESCRIPTION
**Pull request by ezoerner**
This benchmark uses a single publisher with the following configurable parameters:

- number of subscribers
- number of channels
- number of messages per channel per operation
- message byte length

It measures the operation of publishing the messages and waiting for all the subscribers to receive the messages.

There are currently two statically configured benchmarks, a "small" one and a "large" one.

Tested with both jedis and lettuce clients.

This benchmarks pubsub without pattern matching channels.
Once this looks good, it will be straightforward to add additional benchmarks for pattern matching channels.

### CODE REVIEW

**Review by dschneider-pivotal — APPROVED** [review]
This looks good to me. Have you tried changing geode to slow down how long it takes a publish message to get to a subscriber to see if this benchmark will detect the slow down?

**Comment by ezoerner** [comment]
Good idea, I'll try that as a verification. I will also work on a new (smaller) pull request that does pattern matching on the channel names.

**Comment by ezoerner** [comment]
Just by turning on `withVerification=true`, it slows down the subscribers in responding to the pubsub messages by causing them to log a message back to the benchmark controller. This increases the time it takes to process the message significantly, and for the benchmark metrics this is equivalent to geode taking longer to deliver the message to the subscriber. This is indeed reflected in large increase in the average latency reported by the benchmark.

**Comment by ezoerner** [comment]
My concern at this point is that even with no code changes the average latency is showing over a 5% difference in average latency between runs. This could cause the benchmark to fail in CI. This is based on only a couple runs, though. I will try to run it again to get more data.

**Comment by ezoerner** [comment]
I'm good with this being merged

**Comment by ezoerner** [comment]
Closing this PR because it is subsumed by #162

**Pull request closed without merging**
